<a href="https://colab.research.google.com/github/airon14/AIDL/blob/main/58026_Millicheckers_Proofing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1

In this first part it is about creating a activate function for the requirement, we created two parameters which are x and y and also we created four conditions that can be seen when we print or run the code. It successfuly display the output for the NOR gate.

In [ ]:
import numpy as np

In [ ]:
def activation_function(y):
    if y > 0:
        y = 1
    elif y <= 0:
        y = 0
    return y
W = np.array([-1, -1])
b = 1

def p_algo(x):

    y = np.dot(W, x) + b
    y = activation_function(y)
    return y
    
input1 =([0, 0])
input2 =([0, 1])
input3 =([1, 0])
input4 =([1, 1])

In [ ]:
print(" x1  x2  y  gate")
print(" 0   0  ", p_algo(input1)," nor ")
print(" 0   1  ", p_algo(input2)," nor ")
print(" 1   0  ", p_algo(input3)," nor ")
print(" 1   1  ", p_algo(input4)," nor ")

 x1  x2  y  gate
 0   0   1  nor 
 0   1   0  nor 
 1   0   0  nor 
 1   1   0  nor 


#2

For the 2nd requirement x were declared as the input and w1, w2, and w3 were the weights

In [ ]:
x = np.array([1,0])
w1 = np.array([1,-1]),([-1,1])
w2 = np.array([1,2]),([2,1])
w3 = np.array([-1,1])
d= 2.86

#3

For the 3rd requirement function "f_prop" were created for the front propagation. The function contains 4 parameters x, w1, w2, and w3. "tanh" is used for the activation function. It returns or display three values and this are the a1, a2, a3 as seen in the example below.

In [ ]:
def f_prop(x, w1, w2, w3): 
  v1=np.dot(x,w1)
  a1=np.tanh(v1)
  v2=np.dot(a1,w2)
  a2=np.tanh(v2)
  v3=np.dot(a2,w3)
  a3=np.tanh(v3)
  return a1, a2, a3

In [ ]:
a1=f_prop(x, w1, w2, w3)[0]
a1

array([ 0.76159416, -0.76159416])

In [ ]:
a2=f_prop(x, w1, w2, w3)[1]
a2

array([-0.64201499,  0.64201499])

In [ ]:
z = f_prop(x, w1, w2, w3)[2]
z

0.8575549394724464

#4

For the third requirement we created a function "b_prop" and it has five parameters which are x, w1, w2, w3, and y (which is the tanh of a3). The function returns the values of w1, w2, and w3 as seen below.

In [ ]:
y=np.tanh(z)
err = d-y 
err

2.1650042299812915

In [ ]:
def b_prop(x, w1, w2, w3, y): 
  a = 1-y
  b = 1+y
  r = a * b
  de1 = err*r
  r2 = (1-z)*(1+z)
  learning_rate = 0.25
  wn1 = w3 - (learning_rate*de1)*z
  de2 = np.dot(w2,r2)*de1
  wn2 = w2-(learning_rate*de2)*a2
  r3 = (1-a2)*(1+a2)
  de3 = np.dot(w1,r3)*de2
  wn3 = w1 - (learning_rate*de3)*a1
  return (wn1,wn2,wn3)

In [ ]:
b_prop(x, w1, w2, w3, y)[2]

array([[ 1., -1.],
       [-1.,  1.]])

In [ ]:
b_prop(x, w1, w2, w3, y)[1]

array([[1.04753434, 1.90493132],
       [2.09506868, 0.95246566]])

In [ ]:
b_prop(x, w1, w2, w3, y)[0]

array([-1.23995798,  0.76004202])

#5

For the last requirement, we displayed w1, w2, and w3 as the updated weights.

In [ ]:
bprop0=b_prop(x, w1, w2, w3, y)[0]

In [ ]:
bprop1=b_prop(x, w1, w2, w3, y)[1]

In [ ]:
bprop2 = b_prop(x, w1, w2, w3, y)[2]

In [ ]:
print("Updated Weight 1: ",bprop0)
print("Updated Weight 2: ",bprop1)
print("Updated Weight 3: ",bprop2)

Updated Weight 1:  [-1.23995798  0.76004202]
Updated Weight 2:  [[1.04753434 1.90493132]
 [2.09506868 0.95246566]]
Updated Weight 3:  [[ 1. -1.]
 [-1.  1.]]
